config/routes.rb
Rails.application.routes.draw do

  resources :posts
  devise_for :users
  root to: "posts#index"
  get 'pages/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  extend FriendlyId
  belongs_to :user
  has_one_attached :thumbnail
  has_one_attached :banner
  has_rich_text :body

  friendly_id :title, use: :slugged

  validates :title, length: { minimum: 5 }
  validates :body, length: { minimum: 25 }

  self.per_page = 10

  def optimized_image(image,x,y)
    #return image.variant(resize_to_fill[x,y]).processed
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :is_admin!

  private
  def is_admin!
    redirect_to root_path unless current_user && current_user.admin
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :is_admin!, except: [:show, :index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order(created_at: :desc).paginate(page: params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    views = @post.views + 1
    @post.update(views: views)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :views, :body, :thumbnail, :banner)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <!-- <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span> -->
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">BLOG</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= pages_about_path %> ">About</a>
      </li>

    </ul>
    <ul class="navbar-nav ml-auto">
    <% if current_user %>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.email %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if current_user.admin %>
            <a class="dropdown-item" href="#">New Post</a>
            <% end %>
            <a class="dropdown-item" href="<%= edit_user_registration_path %>">Account Settings</a>
            <div class="dropdown-divider"></div>
            <%= link_to "Logout", destroy_user_session_path, class:'dropdown-item', method: :delete %>
            </div>
        </li>
    <% else %>
        <li class="nav-item">
            <%= link_to "Signup", new_user_registration_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
        <%= link_to "Signin", new_user_session_path, class:'nav-link' %>
        </li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">About Me</h1>

        <div class="row">
            <p style="text-align: justify">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nec ultrices dui sapien eget mi proin sed libero. Fringilla phasellus faucibus scelerisque eleifend donec pretium. Turpis egestas integer eget aliquet nibh praesent tristique magna. Magna fringilla urna porttitor rhoncus dolor purus non enim praesent. Dictum sit amet justo donec enim diam. Sit amet cursus sit amet dictum sit amet justo. Euismod quis viverra nibh cras pulvinar. Ultricies integer quis auctor elit sed vulputate mi sit. Dui vivamus arcu felis bibendum ut. Eget magna fermentum iaculis eu non diam phasellus vestibulum. Turpis tincidunt id aliquet risus feugiat in ante metus dictum. Cursus turpis massa tincidunt dui ut ornare.
            <br/>
            <br/>
            Viverra mauris in aliquam sem fringilla. Nulla malesuada pellentesque elit eget. Arcu non odio euismod lacinia at quis risus. Vel pharetra vel turpis nunc eget lorem dolor sed viverra. Lorem ipsum dolor sit amet consectetur. Senectus et netus et malesuada fames ac turpis. Dictumst quisque sagittis purus sit amet volutpat. Faucibus pulvinar elementum integer enim neque volutpat ac tincidunt. Sit amet commodo nulla facilisi. Facilisi nullam vehicula ipsum a. Blandit cursus risus at ultrices mi. Semper quis lectus nulla at volutpat diam ut venenatis tellus. In fermentum posuere urna nec tincidunt praesent semper feugiat.
            </p>
            <hr class="my-4"/>
        </div>
        <div class="btn-group" role="group" aria-label="Basic example">
            <button type="button" onclick="window.location.href = 'https://github.com/deanout';" class="btn btn-secondary">GitHub</button>
            <button type="button" onclick="window.location.href = 'https://instagram.com/deaniocom';" class="btn btn-secondary">Instagram</button>
            <button type="button" onclick="window.location.href = 'https://twitter.com/deaniocom';" class="btn btn-secondary">Twitter</button>
            <button type="button" onclick="window.location.href = 'https://youtube.com/deanin';" class="btn btn-secondary">YouTube</button>
        </div>
    </div>
</div>

app/views/posts/_form.html.erb
<%= form_with model: post, local: true do |f| %>

  <div class="form-inputs">
    <%= f.text_field :title, class:'form-control string' %>

    <%= f.label :thumbnail, class:'form-control' %>
    <%= f.file_field :thumbnail %>
    <%= f.label :banner, class:'form-control' %>
    <%= f.file_field :banner %>
    <%= f.rich_text_area :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
    <div class="row">
        <div class="digg_pagination">
            <%= will_paginate @posts, :container => false %>
        </div>
    </div>


    <% @posts.each do |post| %>
    <div class="row">
        <div class="card mb-3">
            <img class="card-img-top" src="<%= url_for post.optimized_image(post.thumbnail, 586, 180) %>" alt="Blog Post Image Card" />
            <div class="card-body">
                <h5 class="card-title">
                    <%= link_to post.title, post %>
                </h5>
                <p class="card-text">
                    <%= post.body.to_plain_text.truncate_words(50) %>
                </p>
                <p class="card-text">
                    <small class="text-muted">
                        <%= post.updated_at.strftime("%A, %B %e, %Y") %> by
                        <%= post.user.email %> | <%= pluralize(post.views, "View") %> | 0 comments
                    </small>
                </p>
            </div>
        </div>
    </div>
    <% end %>
</div>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div style="width:100%; height: 300px; overflow-y:hidden">
  <%= image_tag(@post.banner, style:'width:100%') %>
</div>
<div class="container" style="margin-top: 2em">
  <div class="row">
    <div class="jumbotron" style="width:100%">
      <h1 class="display-4">
        <%= link_to @post.title, root_path %>
      </h1>
      <p class="lead">
        <%= @post.updated_at.strftime("%A, %B %e, %Y") %> by <%= @post.user.email %> | <%= pluralize(@post.views, "View") %>
      </p>
      <hr class="my-4" />
      <div class="post_body">
        <%= @post.body %>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>